const frasesDiego = [
    "Mis sueños son dos. Mi primer sueño es jugar en el Mundial, y el segundo es salir campeón de Octava y lo que siga en el campeonato este (con Argentinos)",
    "Ganarle a River es como que tu mamá te venga a despertar con un beso a la mañana",
    "Pensé que venía Berlusconi y me encontré con el cartonero Báez",
    "A Grondona se le escapó la tortuga",
    "Me siento más sólo que Kung Fu",
    "Lástima no se le tiene a nadie, maestro. Pelealo, tenele bronca, pero lástima a nadie",
    "¿Que el hincha se muere por un abrazo entre Maradona y Riquelme? No. Decile que se va a quedar vivo",
    "Si los novios de mis hijas las hacen llorar dos o tres veces, van a tener un accidente",
    "Grondona me mintió, Bilardo me traicionó",
    "Cuando dicen que soy Dios yo respondo que están equivocados: soy un simple jugador de fútbol. Dios es Dios y yo soy Diego",
    "Sólo les pido que me dejen vivir mi propia vida. Yo nunca quise ser un ejemplo",
    "Si está vacío, que se llene, porque no se puede traicionar a los hinchas",
    "Creeme que me cortaron las piernas",
    "Yo me equivoqué y pagué, pero la pelota no se mancha",
    "Coppola es vivísimo. Fuma debajo del agua",
    "Si no me va a contestar es un botón",
    "Si voy al banco es para sacar plata, fiera",
    "Pelé debutó con un pibe… Y le pegó a la jermu",
    "Si a Sampaoli le tirás la pelota, te la devuelve con la mano",
    "Más falso que dólar celeste",
    "Bilardo es como Berisso: está detrás de La Plata",
    "A Toresani: Segurola y Habana 4310, séptimo piso. Y vamos a ver si me dura 30 segundos",
    "La Selección es un Rolls Royce lleno de tierra, hay que limpiarlo",
    "El juez Bernasconi es muy rápido: es capaz de meterle un supositorio a una liebre",
    "Para jugar contra Australia nos daban café veloz",
    "Me había propuesto hacerle dos goles a Gatti, pero ahora que me dijo 'gordito' le voy a meter cuatro",
    "Pasman, vos también la tenés adentro",
    "Llegar al área y no poder patear al arco es como bailar con tu hermana",
    "Yo no soy ningún mago: los magos son los que están en Fiorito porque viven con mil pesos por mes",
    "Yo quería ir a Estados Unidos, pero el cabeza de termo de Clinton no me deja entrar",
    "Cuando escucho a Batista decir que Messi ahora es feliz, me pregunto dónde estaba durante los días de convivencia en Pretoria. Lionel conmigo también fue feliz. ¿Qué hizo Batista, se disfrazó de Piñón Fijo?",
    "Cuando entré al Vaticano y vi todo ese oro me convertí en una bola de fuego",
    "¿Cómo hice el gol? Lo hizo la mano de Dios",
    "Fui, soy y seré drogadicto",
    "Quedar afuera de un Mundial sólo es comparable a ver cómo le peguen a tu vieja y vos estás atado a una silla",
    "Los boludos son como las hormigas, están en todas partes del mundo",
    "Ser Maradona es hermoso. Soy un tipo normal que por hacerle un gol a los ingleses, que nos mataron a los pibes en Malvinas, hoy la gente me conoce. Pero soy el tipo más normal",
    "Un árabe me ofreció una casa con zoológico y le dije: 'esperá maestro, ¿Quién le da de comer al león? Pará, je' ",
    "La rinoscopía, el pelo corto... Un día los muchachos de la Selección se van a rascar un huevo y Passarella se los va a mandar a cortar",
    "Mis hijas legítimas son Dalma y Gianinna. Los demás son hijos de la plata o de la equivocación",
    "Un Boca-River es distinto a todo. Es como dormir con Julia Roberts",
    "Crecí en un barrio privado de Buenos Aires. Privado de luz, de agua, de teléfono",
    "En la clínica hay uno que se cree Napoleón y otro Robinson Crusoe. ¡Y a mí no me creen que soy Maradona",
    "Esto te da vida, el fútbol te da vida",
    "No quiero dramatizar, pero créeme que me cortaron las piernas",
    "Jorge Valdano tiene más mentira que el truco",
    "No hay negro que no destiña…",
    "Al principio la droga te pone eufórico. Es como ganar un campeonato. Y pensás: mañana qué importa, si hoy gané el campeonato",
    "A Pele ya le gané, ahora que vuelva al museo",
    "Hoy no hablo muchachos. Tengo menos palabras que un telegrama",
    "A los que no creían en este equipo, con el perdón de las damas, que la chupen. Que la sigan chupando",
    "Yo soy o blanco o negro, gris no voy a ser en mi vida",
    "Cristiano Ronaldo hace un gol y te vende un champú",
    "Boca tiene menos definición que la televisión que teníamos en Fiorito",
    "Lo único que falta es que un plantamandioca como Chilavert nos diga a los argentinos lo que tenemos que hacer",
    "Pelé es un esclavo. Le vendió su corazón a la FIFA",
    "Blatter me quiere como un hijo. Sí… como un hijo de puta",
    "Cuando dicen que soy Dios, yo respondo que están equivocados: soy un simple jugador de futbol. Dios es Dios y yo soy Diego",
    "¿Cómo hice el gol? Lo hizo la mano de Dios",
    "Pase lo que pase y dirija quien dirija, la camiseta número 10 será siempre mía",
    "Jugar sin público es jugar adentro de un cementerio",
    "Si me muero, quiero volver a nacer y quiero ser futbolista. Y quiero volver a ser Diego Armando Maradona. Soy un jugador que le ha dado alegría a la gente y con eso me basta y me sobra"
];

module.exports = frasesDiego;
